import {
  WinterTitleSlide,
  OfferingSlide,
  AudienceSlide,
  SessionsSlide,
  FormatSlide,
  TimetableSlide,
  ToolboxSlide,
  SetupSlide,
  SurveySlide,
  RegisterSlide,
  TeamSlide,
  DisclaimerSlide,
  ThankYouSlide,
} from './src/slides/WinterSlides.jsx'

export default {
  id: 'agentic-data-winter-bootcamp',
  title: 'Agentic Data Engineering Winter Bootcamp',
  subtitle: 'Sleigh your data backlog. From vibe coding to spec-driven data engineering.',
  description: 'Sleigh your data backlog. From vibe coding to spec-driven data engineering with GitHub Copilot and Microsoft Fabric.',
  icon: '❄️',
  accent: '#8fd8ff',
  theme: 'dark',
  appearance: 'dark',
  order: 1,
  slides: [
    WinterTitleSlide,
    OfferingSlide,
    AudienceSlide,
    SessionsSlide,
    FormatSlide,
    TimetableSlide,
    ToolboxSlide,
    SetupSlide,
    SurveySlide,
    RegisterSlide,
    TeamSlide,
    DisclaimerSlide,
    ThankYouSlide,
  ],
}
